/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        
        ButtonGroup ob=new ButtonGroup();
        ob.add(rbMale);
        ob.add(rbFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbFirstName = new javax.swing.JLabel();
        lbLastName = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbBirthday = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbCountry = new javax.swing.JLabel();
        lbPasword = new javax.swing.JLabel();
        lbConfirmPasword = new javax.swing.JLabel();
        tvFirstName = new javax.swing.JTextField();
        tvLastName = new javax.swing.JTextField();
        tvEmail = new javax.swing.JTextField();
        tvUserName = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        cbCountry = new javax.swing.JComboBox<String>();
        tvConfirmPassword = new javax.swing.JTextField();
        tvPassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShow = new javax.swing.JTable();
        btSignUp = new javax.swing.JButton();
        lbNotification = new javax.swing.JLabel();
        tvBirthday = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbFirstName.setText("First Name");

        lbLastName.setText("Last Name");

        lbUserName.setText("User name");

        lbEmail.setText("Email");

        lbBirthday.setText("Birthday");

        lbGender.setText("Gender");

        lbCountry.setText("Country");

        lbPasword.setText("Pasword");

        lbConfirmPasword.setText("Confirm Pasword");

        tvEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvEmailActionPerformed(evt);
            }
        });

        rbMale.setText("Male");

        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Country", "Afganistan", "Bangladesh", "Bhutan", "Bahrain", "Canada", "Denmark", "Ethuipia", "France", "Germany", "Holand", "India", "Italy", "Japan", "Kajastan", "Maloysia", "Nepal", "Pakistan", "Quba", "Rassia", "South Afrika", "Swizer Land", "Thailand", "Ujbekistan", "Vietnam", " " }));

        tvPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvPasswordActionPerformed(evt);
            }
        });

        tbShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email", "birthday", "Gender", "Country", "Password"
            }
        ));
        jScrollPane1.setViewportView(tbShow);

        btSignUp.setText("Signup");
        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });

        lbNotification.setBackground(new java.awt.Color(204, 204, 255));
        lbNotification.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFirstName)
                            .addComponent(lbEmail)
                            .addComponent(lbLastName)
                            .addComponent(lbUserName)
                            .addComponent(lbBirthday)
                            .addComponent(lbGender)
                            .addComponent(lbConfirmPasword)
                            .addComponent(lbPasword)
                            .addComponent(lbCountry))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbCountry, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbFemale)))
                                .addGap(75, 75, 75)
                                .addComponent(lbNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tvBirthday, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(tvLastName)
                                    .addComponent(tvUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btSignUp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbFirstName)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tvFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLastName)
                                .addGap(18, 18, 18)
                                .addComponent(lbUserName)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tvLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tvUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(tvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbBirthday))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tvBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGender)
                            .addComponent(rbMale)
                            .addComponent(rbFemale))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCountry)
                            .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPasword)
                    .addComponent(tvPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmPasword)
                    .addComponent(tvConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSignUp)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvPasswordActionPerformed

    private void tvEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvEmailActionPerformed

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbShow.getModel();
        if(!tvFirstName.getText().trim().equals("") &&!tvLastName.getText().trim().equals("") && !tvUserName.getText().trim().equals("") && !tvEmail.getText().trim().equals("") && !tvBirthday.getText().toString().trim().equals("") && !cbCountry.getSelectedItem().toString().trim().equals("") && !tvPassword.getText().trim().equals("")  && !tvConfirmPassword.getText().trim().equals("") && rbFemale.isSelected()){
            model.addRow(new Object[]{tvFirstName.getText(),tvLastName.getText(),tvEmail.getText(),tvBirthday.getText(),rbFemale.getText(),cbCountry.getSelectedItem(),tvPassword.getText()});
            
            tvFirstName.setText("");
            tvLastName.setText("");
            tvUserName.setText("");
            tvEmail.setText("");
            tvPassword.setText("");  
            tvConfirmPassword.setText("");
            lbNotification.setText("Signup successful..!!");
        }
        
        if(!tvFirstName.getText().trim().equals("") &&!tvLastName.getText().trim().equals("") && !tvUserName.getText().trim().equals("") && !tvEmail.getText().trim().equals("") && !tvBirthday.getText().toString().trim().equals("") && !cbCountry.getSelectedItem().toString().trim().equals("") && !tvPassword.getText().trim().equals("")  && !tvConfirmPassword.getText().trim().equals("") && rbMale.isSelected()){
            model.addRow(new Object[]{tvFirstName.getText(),tvLastName.getText(),tvEmail.getText(),tvBirthday.getText(),rbMale.getText(),cbCountry.getSelectedItem(),tvPassword.getText()});
            
            tvFirstName.setText("");
            tvLastName.setText("");
            tvUserName.setText("");
            tvEmail.setText("");
            tvPassword.setText("");  
            tvConfirmPassword.setText("");
            lbNotification.setText("Signup successful..!!");
        }
        else{
            lbNotification.setText("Signup failed...");
        }
    }//GEN-LAST:event_btSignUpActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBirthday;
    private javax.swing.JLabel lbConfirmPasword;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbNotification;
    private javax.swing.JLabel lbPasword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTable tbShow;
    private javax.swing.JTextField tvBirthday;
    private javax.swing.JTextField tvConfirmPassword;
    private javax.swing.JTextField tvEmail;
    private javax.swing.JTextField tvFirstName;
    private javax.swing.JTextField tvLastName;
    private javax.swing.JTextField tvPassword;
    private javax.swing.JTextField tvUserName;
    // End of variables declaration//GEN-END:variables
}
